### PR TITLE
support binary data

### PR DESCRIPTION
**Pull request by ibigbug**

### CODE REVIEW

**Comment by Marfusios** [comment]
Hello, 

thank you for the PR, could you please fix [unit tests](https://travis-ci.org/Marfusios/websocket-client/builds/503506792)? 

I will make a few integration tests and going to publish it under a new major version because it is breaking change.

**Comment by ibigbug** [comment]
sounds good, will do that

**Comment by ibigbug** [comment]
tests passed

**Comment by Marfusios** [comment]
I did a few changes in the separate branch. Merging this.

**Pull request merged**
